name: Docs Quality

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
      - ".github/workflows/docs-quality.yml"
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".github/workflows/docs-quality.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  link-check:
    name: Check Documentation Links
    uses: zavestudios/platform-pipelines/.github/workflows/link-check.yml@c0159f042136961310d5dce6ebe780805f7e9781
    with:
      lychee_args: "--verbose --no-progress --config .github/lychee.toml"
